services:

  api_gateway:
    build:
      context: ./NotifyHub.Gateway
      dockerfile: ./NotifyHub.Gateway/Dockerfile 
    container_name: NotifyHub.Gateway
    ports:
      - "8088:8080"
    networks:
      - notify_hub_network
    depends_on:
      - webapi
      - notification_microservice
      - outbox_processor
    
  webapi:
    build:
      context: ./NotifyHub
      dockerfile: NotifyHub.WebApi/Dockerfile 
    container_name: NotifyHub.WebApi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Postgres=Host=db;Port=5432;Username=postgres;Password=notify_hub;Database=notify_hub_db;
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - notify_hub_network
    volumes:
      - data_protection:/root/.aspnet/DataProtection-Keys
    restart: always

  notification_microservice:
    build:
      context: ./NotifyHub.NotificationService
      dockerfile: NotifyHub.NotificationService.WebApi/Dockerfile 
    container_name: NotifyHub.NotificationService.WebApi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Postgres=Host=notify_db;Port=5432;Username=postgres;Password=notify_hub_notifications;Database=notify_hub_notifications_db;
    depends_on:
      notify_db:
        condition: service_healthy
    ports:
      - "8084:8080"
    networks:
      - notify_hub_network
    volumes:
      - data_protection:/root/.aspnet/DataProtection-Keys
    restart: always

  outbox_processor:
    build:
      context: ./NotifyHub.OutboxProcessor
      dockerfile: NotifyHub.OutboxProcessor.WebApi/Dockerfile 
    container_name: NotifyHub.OutboxProcessor
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Postgres=Host=outbox_db;Port=5432;Username=postgres;Password=notify_hub_outbox;Database=notify_hub_outbox_db;
      - ConnectionStrings__Redis=outbox_redis:6379
    depends_on:
      outbox_db:
        condition: service_healthy
      outbox_redis: 
        condition: service_healthy
    ports:
      - "8086:8080"
    networks:
      - notify_hub_network
    volumes:
      - data_protection:/root/.aspnet/DataProtection-Keys
    restart: always

  outbox_redis:
    image: redis:7-alpine
    container_name: NotifyHub.OutboxProcessor.Redis
    ports:
      - "6379:6379"
    networks:
      - notify_hub_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  outbox_db:
    image: postgres:16
    container_name: NotifyHub.OutboxProcessor.PostgresSQL
    environment:
      TZ: UTC
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: notify_hub_outbox
      POSTGRES_DB: notify_hub_outbox_db
    command: ["postgres", "-c", "timezone=UTC"]
    volumes:
      - outbox_db_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - notify_hub_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5

  notify_db:
    image: postgres:16
    container_name: NotifyHub.NotificationService.PostgresSQL
    environment:
      TZ: UTC
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: notify_hub_notifications
      POSTGRES_DB: notify_hub_notifications_db
    command: ["postgres", "-c", "timezone=UTC"]
    volumes:
      - notify_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - notify_hub_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5

  db:
    image: postgres:16
    container_name: NotifyHub.PostgresSQL
    environment:
      TZ: UTC
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: notify_hub
      POSTGRES_DB: notify_hub_db
    command: ["postgres", "-c", "timezone=UTC"]
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - notify_hub_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5

  zookeeper:
    restart: always
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    networks:
      - notify_hub_network
    volumes:
      - "zookeeper-volume:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    restart: always
    image: docker.io/bitnami/kafka:3.3
    ports:
      - "9093:9093"
    networks:
      - notify_hub_network
    volumes:
      - "kafka-volume:/bitnami"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: always
    ports:
      - "8090:8080"
    networks:
      - notify_hub_network
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
      - DYNAMIC_CONFIG_ENABLED=true
    depends_on:
      - kafka
      - zookeeper

volumes:
  db_data:
  kafka-volume:
  notify_db_data:
  outbox_db_data:
  data_protection:
  zookeeper-volume:

networks:
  notify_hub_network:
    driver: bridge